### ISSUE TITLE
客户端mod和服务器端mod不同

### ISSUE THREAD

**Issue by laodonge** [Project-StarryNight/StarryNight_Pray#12]
客户端mod和服务器端mod不同
![QQ图片20220404125825](https://user-images.githubusercontent.com/77783957/161476809-46414676-9135-4ad7-b39f-dc7b5657b464.png)

**Comment by KasumiNova** [comment]
将会在1.1.3更新中修复这个问题。

**Comment by KasumiNova** [comment]
在 1.2.0 中修复了这个问题。
