### ISSUE TITLE
HMCL无法打开1.2.0.1-alpha版本整合包

### ISSUE THREAD

**Issue by pizeroLOL** [Project-StarryNight/StarryNight_Pray#39]
系统版本：kubuntu22.04
运行环境：java8-openjdk
[hmcl-exported-logs-2022-04-21T13-15-17.log](https://github.com/Project-StarryNight/StarryNight_Pray/files/8527423/hmcl-exported-logs-2022-04-21T13-15-17.log)

**Comment by pizeroLOL** [comment]
群内1.2.0整合包正常

**Comment by KasumiNova** [comment]
github的整合包格式有误，会在下版本修复

**Comment by S-Leader** [comment]
> github的整合包格式有误，会在下版本修复

需要我来导出吗
