### ISSUE TITLE
无法获取赛特斯水晶

### ISSUE THREAD

**Issue by Dabai1025** [Project-StarryNight/StarryNight_Pray#57]
大概是因为矿脉被自定义生成，而矿脉中没有赛特斯石英水晶矿石，只有充能赛特斯石英矿石。
但是 TC6 的附属：神秘能源一向研究需要赛特斯石英水晶。
经各种合成方式，均无法获取。
另：赛特斯水晶块也无法正常合成。
![2](https://user-images.githubusercontent.com/65448593/165966981-1f77ce06-1480-459f-babb-ef732489dcb0.png)
![3](https://user-images.githubusercontent.com/65448593/165966986-a4318191-a598-4c06-88e3-23d10dccbae1.png)

![1](https://user-images.githubusercontent.com/65448593/165966971-72972d35-6363-4382-9336-0d9b1499de30.png)

**Comment by KasumiNova** [comment]
神秘能源研究存在一些问题，这个问题将会从神秘开始修复，而不是赛特斯水晶。

**Comment by Dabai1025** [comment]
好的。
