### ISSUE TITLE
希望缩减打开时间和添加可选mod文件夹或清单

### ISSUE THREAD

**Issue by pizeroLOL** [Project-StarryNight/StarryNight_Pray#64]
1. 我的Dell燃7560将stp放在固态盘中打开时间需要至少9分钟，希望缩减打开时间
2. 我在 #50 提交的kokolinux可能在打包时会默认启用，而在库中默认是禁用的，可能会导致用户无法开启游戏。以及jei与hei冲突，还有可能有一些不是很必要的mod。所以希望开一个可选mod文件夹或者清单

**Comment by KasumiNova** [comment]
1. 可以提供一下Caliper的 Load Times 报告吗
2. 已添加到计划中

**Comment by pizeroLOL** [comment]
> 1. 可以提供一下Caliper的 Load Times 报告吗
> 2. 已添加到计划中

请问

**Comment by pizeroLOL** [comment]
> 1. 可以提供一下Caliper的 Load Times 报告吗
> 2. 已添加到计划中

请问Caliper的 Load Times 报告在哪里，我明天如果有时间看看

**Comment by pizeroLOL** [comment]
刚刚一不小心碰到了

**Comment by pizeroLOL** [comment]
> 1. 可以提供一下Caliper的 Load Times 报告吗
> 2. 已添加到计划中
[load-times.md](https://github.com/Project-StarryNight/StarryNight_Pray/files/8646258/load-times.md)

**Comment by pizeroLOL** [comment]
奇怪的东西增加了

**Comment by KasumiNova** [comment]
怪怪的..全是0.0s

**Comment by pizeroLOL** [comment]
> 怪怪的..全是0.0s
[load-times - 副本.md](https://github.com/Project-StarryNight/StarryNight_Pray/files/8646481/load-times.-.md)

HMCL似乎没有记录

**Comment by KasumiNova** [comment]
JEI 与 HEI 的冲突问题已经修复，现在两个可选MOD会放在独立的文件夹供玩家选择。
