### ISSUE TITLE
宏伟之木无法正常变为活木的bug

### ISSUE THREAD

**Issue by haoduor** [Project-StarryNight/StarryNight_Pray#71]
[scripts](https://github.com/Project-StarryNight/StarryNight_Pray/tree/master/scripts)/[mods](https://github.com/Project-StarryNight/StarryNight_Pray/tree/master/scripts/mods)/[botania](https://github.com/Project-StarryNight/StarryNight_Pray/tree/master/scripts/mods/botania)/botania.zs    240行
```
//活木
PureDaisy.removeRecipe(<botania:livingwood>);
PureDaisy.addRecipe(<thaumcraft:log_greatwood>, <botania:livingwood>, 30);
```
无法正确的将所有朝向的宏伟之木变为活木
可以改为下列代码以修复问题
```
//活木
PureDaisy.removeRecipe(<botania:livingwood>);
PureDaisy.addRecipe(<thaumcraft:log_greatwood>, <botania:livingwood>, 30);
PureDaisy.addRecipe(<thaumcraft:log_greatwood>:1, <botania:livingwood>, 30);
PureDaisy.addRecipe(<thaumcraft:log_greatwood>:2, <botania:livingwood>, 30);
```

**Comment by KasumiNova** [comment]
好主意，不过`:1 :2`的位置不对（

**Comment by KasumiNova** [comment]
1.3 Alpha 中已修复
